### ISSUE TITLE
Tracking issue: Required schema additions to make new lints possible

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#241]
In approximate order of increasing difficulty:

- [ ] expose auto-trait / unsafe trait info on [`type Trait`](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/0b1f021c22aab6e48f38156e52c7b8331447149a/src/rustdoc_schema.graphql#L382)
    - new lints enabled by this:
        - [trait became unsafe](https://github.com/obi1kenobi/cargo-semver-checks/issues/231) (so its `impl` blocks need to be `unsafe impl` now)

- [ ] expose constants: [`const` and `static` values](https://doc.rust-lang.org/stable/rust-by-example/custom_types/constants.html)
    - even without type information, there are lints to be checked here
    - new lints enabled by this:
        - module-level `const` missing (cannot be imported, so renamed or deleted)
        - module-level `static` missing (cannot be imported, so renamed or deleted)
        - `const` in type's `impl` block missing (cannot be imported, so renamed or deleted)
        - `static` in type's `impl` block missing (cannot be imported, so renamed or deleted)

- [ ] expose associated type info on [`type Trait`](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/0b1f021c22aab6e48f38156e52c7b8331447149a/src/rustdoc_schema.graphql#L382)
    - even without type information, we can still write lints about this
    - new lints enabled by this:
        - associated type missing (renamed or deleted, will break `Trait::Assoc` uses)

- [ ] expose enum variant fields on [`interface Variant`](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/0b1f021c22aab6e48f38156e52c7b8331447149a/src/rustdoc_schema.graphql#L192)
    - they are already available on `type StructVariant`
    - the edge on `type PlainVariant` should exist but never produce any vertices
    - the edge on `type TupleVariant` should produce fields similarly to how tuple structs produce their fields
    - new lints enabled by this:
        - tuple variant field removed
        - exhaustive tuple variant field added

- [ ] expose field ordering information
    - probably via a separate edge to a new type, like `field_index: [FieldIndex]` where that new type contains the field index number and points to a `StructField`
    - new lints enabled by this:
        - `repr(C)` plain struct has its fields reordered

- [ ] expose supertrait edge on [`type Trait`](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/0b1f021c22aab6e48f38156e52c7b8331447149a/src/rustdoc_schema.graphql#L382) which should probably point to [`type ImplementedTrait`](https://github.com/obi1kenobi/trustfall-rustdoc-adapter/blob/0b1f021c22aab6e48f38156e52c7b8331447149a/src/rustdoc_schema.graphql#L562)
    - new lints enabled by this:
        - [trait removed supertrait](https://github.com/obi1kenobi/cargo-semver-checks/issues/232)

- [ ] expose type information (including generics, lifetimes, impl trait, trait bounds, etc.)
    - this is quite hard, but would unlock a ton of new lints
    - new lints enabled by this (partial list, surely there are more):
        - plain struct field changes type
        - tuple struct field changes type
        - enum struct variant field changes type
        - enum tuple variant field changes type
        - `const` value changed type
        - `static` value changed type
        - function argument changes type to a different non-generic type
            - non-generic because then it's definitely breaking
            - if the type is generic then it's more complex to determine whether the change is breaking
        - function return value changes type to a different non-generic type
            - non-generic: same as above
        - associated type in trait implementation changed type to a different non-generic type
            - non-generic: same as above
