### ISSUE TITLE
Tracking issue: import handling revamp

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#288]
- [ ] support type aliases: #215
- [ ] support renaming re-exports: #42 and #202
- [x] don't crash on recursive re-exports: #152 and #287
- [x] support glob imports and glob re-exports: #34

Type alias support is more valuable than renaming re-exports, per https://github.com/libp2p/rust-libp2p/pull/2647#issuecomment-1343467075

**Comment by obi1kenobi** [comment]
Here are some of the import shenanigans we should correctly handle:
https://github.com/obi1kenobi/trustfall-rustdoc-adapter/compare/imports_test_suite
