### ISSUE TITLE
Added deprecated attribute API lint, minor incompatibility level

### ISSUE THREAD

**Issue by epage** [obi1kenobi/cargo-semver-checks#57]
Semver says deprecations are minor changes.

Reference: https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute

Will require separate checks for:
- [x] struct, enum
- [x] union
- [x] trait: #1092
- [x] fn: #1093 
- [x] const / static (`GlobalValue`): #1101 
- [x] trait methods: #1098
- [x] `ImplOwner` (struct/enum/union) methods: #1130
- [x] `ImplOwner` associated constants: #1131
- [x] trait associated types: #1099
- [x] trait associated constants: #1100
- [x] enum variants: #1179 
- [x] fields within enum struct variants: #1180 
- [x] fields within enum tuple variants: #1202
- [x] struct fields: #1125
- [x] declarative macros: #1102
- [x] proc macros: #1118

**Comment by pksunkara** [comment]
@obi1kenobi It hasn't been implemented for `union`. You might want to separate it out from `struct & enum` in the issue description.

**Comment by obi1kenobi** [comment]
Done, thanks!

**Comment by Frank-III** [comment]
`struct fields` should be marked done: #1125. the only two missing parts have PR opened.

**Comment by obi1kenobi** [comment]
Sweet! Thank you for all your work, that's a lot of boxes you've checked!

Might you be interested in doing a bit of schema extension next, to unlock even more lints elsewhere? If so, adding "field ordering" information to struct fields and enum tuple/struct variant fields can unlock ~10ish more new lints. This is because changing the order of struct fields (e.g. swapping which field is first and which is second) can be a major breaking change in some circumstances.

**Comment by Frank-III** [comment]
> Sweet! Thank you for all your work, that's a lot of boxes you've checked!

Thank you for your guidance, the more lint I added the more I realized how important c-s-c would be in the rust ecosystem!

> Might you be interested in doing a bit of schema extension next, to unlock even more lints elsewhere? If so, adding "field ordering" information to struct fields and enum tuple/struct variant fields can unlock ~10ish more new lints. This is because changing the order of struct fields (e.g. swapping which field is first and which is second) can be a major breaking change in some circumstances.

Definitely yes. Could you explain more about how it would be implemented? like adding a field to the `StructField` / `Variant` type ? and for the lints, we need to check if say a struct's field's order is changed, and report something like:
- "field `a` in `struct` order has changed"
- "field `a` in `struct` order has changed"

**Comment by obi1kenobi** [comment]
Here's an issue describing this in more detail and giving one example of a lint: https://github.com/obi1kenobi/trustfall-rustdoc-adapter/issues/758

There are more lints that use order info in #5. I'll try to organize them into a separate issue with individual checkboxes similar to this one.

Off-topic: You are very good at this work! Consider applying for [a Rust-themed Google Summer of Code of project](https://github.com/rust-lang/google-summer-of-code), if you don't already have other plans this summer! There are some `cargo-semver-checks` projects on that list, and you can always pitch your own as well. Happy to chat more if that sounds interesting!

**Comment by Frank-III** [comment]
> Off-topic: You are very good at this work! Consider applying for [a Rust-themed Google Summer of Code of project](https://github.com/rust-lang/google-summer-of-code), if you don't already have other plans this summer! There are some cargo-semver-checks projects on that list, and you can always pitch your own as well. Happy to chat more if that sounds interesting!

Wow, I did not know that! would definitely apply for it and see what I could build for the summer, c-s-c seems to be something I wanna work for!
