### ISSUE TITLE
New lints: Breaking changes in macros

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-checks#946]
There are several ways to cause a breaking change by changing macro item definitions that we can lint for today:
- [x] removing a declarative macro that used to exist (#966)
- [x] removing a function-like proc macro that used to exist (#1021)
- [x] removing an attribute proc macro that used to exist (#1026)
- [x] removing a derive proc macro that used to exist (#1027)
- [x] removing a [helper attribute](https://doc.rust-lang.org/reference/procedural-macros.html#derive-macro-helper-attributes) from a derive proc macro (#1028)
- [x] declarative macro became `#[doc(hidden)]` (#1029)
- [x] declarative macro is no longer `#[macro_export]` but is not `#[doc(hidden)]` -- variant of #966 in that the macro can't be used, but it's still defined, just local to its defining crate (#1031)
- [x] proc macro became `#[doc(hidden)]` (#1050)

Relevant docs we can use as references in the lints:
- declarative macros: https://doc.rust-lang.org/reference/macros-by-example.html
- procedural (proc) macros: https://doc.rust-lang.org/reference/procedural-macros.html

The lints here will be similar to existing "item missing" lints (e.g. [enum missing](https://github.com/obi1kenobi/cargo-semver-checks/blob/main/src/lints/enum_missing.ron), [enum variant missing](https://github.com/obi1kenobi/cargo-semver-checks/blob/main/src/lints/enum_variant_missing.ron)), with one important difference: macros are always at the top level of the crate that defined them. They don't have importable paths, so our matching doesn't need the `importable_path` edge like for other items and can instead simply rely on the macro's own name.

Make sure to check out our [contributing guide](https://github.com/obi1kenobi/cargo-semver-checks/blob/main/CONTRIBUTING.md), and take a look at what [prior lints' merged PRs looked like](https://github.com/obi1kenobi/cargo-semver-checks/pull/844) so you know what to expect. It's easier than you think!

**Comment by miikka** [comment]
I'll give a go at implementing "removing a declarative macro that used to exist".
